{
 "title": "ASP.NET Core",
 "description": "ASP .NET Core 기반 API 서버의 기본 데이터 (prometheus-net 호환)",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_requests_in_progress,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_requests_in_progress{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Thread Pool (Threads / Queue / Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_threadpool_num_threads{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "dotnet_threadpool_queue_length{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Queue Length"
    },
    {
     "expr": "rate(dotnet_threadpool_throughput_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Throughput/s"
    }
   ]
  },
  {
   "title": "Requests Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(http_requests_received_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(\r\n  sum(\r\n    increase(http_requests_received_total{job=~\"$job\",instance=~\"$instance\"}[$__range])\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Memory (System)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Mem Used"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum by (le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Total 5xx Responses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_received_total{code=\"5xx\",job=~\"$job\",instance=~\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "GC Heap (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(dotnet_gc_heap_size_bytes{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "GC Heap"
    }
   ]
  },
  {
   "title": "Top 10 Error Endpoints (4xx+5xx)",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  ceil(\r\n    sum by (endpoint, method, controller, action) (\r\n      increase(http_requests_received_total{code=~\"4xx|5xx\",controller!=\"\",action!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__range])\r\n    )\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "MySQL Connection Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(mysql_global_status_threads_connected{job=\"mysql\"}[1m]) / on(instance) mysql_global_variables_max_connections{job=\"mysql\"}",
     "legendFormat": "used / max"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  ceil(\r\n    sum by (endpoint, method, controller, action) (\r\n      increase(http_requests_received_total{controller!=\"\",action!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__range])\r\n    )\r\n  )\r\n)\r\n"
    }
   ]
  }
 ]
}