global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: apiserver
    static_configs:
      - targets: ["localhost:5274"] 
    metric_relabel_configs:
      # .NET Meter 기반 시계열 숨기기 (저장 안 함)
      - source_labels: [__name__]
        regex: "microsoft_aspnetcore_.*|system_runtime_.*"
        action: drop