global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: apiserver
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5274"]

    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: "^(api_request_duration_seconds(_.*)?|active_sessions|login_total|stage_clear_total|http_requests_received_total|http_requests_in_progress|http_request_duration_seconds(_.*)?|microsoft_aspnetcore_hosting_http_server_.*|microsoft_aspnetcore_server_kestrel_.*|dotnet_.*|system_runtime_.*|node_.*)$"

  - job_name: mysql
    static_configs:
      - targets: ["mysqld-exporter:9104"]
